name: Essentials
version: 1.0.0
author: DiabolicaTrix
main: com.github.DiabolicaTrixPlugins.Essentials
commands:
 join:
   description: "Join a game !"
 exit:
   description: "Exit a game !"
    